# modules/desktop/term/foot.nix
#
# TODO

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let termCfg = config.modules.desktop.term;
    cfg = termCfg.foot;
    defaultSettings = {
      main.font = "${termCfg.font.name}:size=${toString termCfg.font.size}";
    };
in {
  options.modules.desktop.term.foot = with types; {
    enable = mkBoolOpt false;
    settings = mkOpt (attrsOf attrs) {};
  };

  config = mkIf cfg.enable {
    fonts.packages = [ termCfg.font.package ];

    user.packages = with pkgs; [
      foot
      libsixel  # image support in foot
      termCfg.font.package
    ];

    modules.shell.tmux.term = mkForce "foot";

    home.configFile = {
      "foot/foot.ini".text = ''
        # config/foot/foot.ini
        # This was automatically generated by NixOS and my dotfiles
        include=${config.home.configDir}/foot/foot.global.ini
        include=${config.home.configDir}/foot/foot.local.ini
      '';
      "foot/foot.global.ini".source = "${hey.configDir}/foot/foot.ini";
      "foot/foot.local.ini".text = generators.toINI {} (recursiveUpdate defaultSettings cfg.settings);
    };
  };
}
